name: kfazer3
description: Task management and distribution.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  badges: ^2.0.3
  collection: ^1.16.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_layout_grid: ^2.0.1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.0.0-dev.9
  go_router: ^3.1.1
  http: ^0.13.4
  infinite_scroll_pagination: ^3.2.0
  intl: ^0.17.0
  ms_undraw: ^3.1.0+2
  rxdart: ^0.27.4
  skeletons: ^0.0.3
  smart_space: ^0.1.2
  url_launcher: ^6.1.5

dev_dependencies:

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

# Custom app icon. For more info see: https://pub.dev/packages/flutter_launcher_icons
# flutter_icons:
#   ios: true
#   android: true
#   remove_alpha_ios: true
#   image_path_ios: "assets/app-icon.png"
#   image_path_android: "assets/app-icon.png"
#   # https://github.com/fluttercommunity/flutter_launcher_icons/issues/144
#   adaptive_icon_background: "assets/app-icon-background.png"
#   adaptive_icon_foreground: "assets/app-icon-foreground.png"
flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true
  # assets:
  # Add assets from the images directory to the application.
  # - assets/
