name: kfazer3
description: Task management and distribution.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  collection: ^1.16.0
  flutter:
    sdk: flutter
  flutter_layout_grid: ^2.0.1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^1.0.4
  go_router: ^3.1.1
  ms_undraw: ^3.1.0+2
  smart_space: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# Custom app icon. For more info see: https://pub.dev/packages/flutter_launcher_icons
# flutter_icons:
#   ios: true
#   android: true
#   remove_alpha_ios: true
#   image_path_ios: "assets/app-icon.png"
#   image_path_android: "assets/app-icon.png"
#   # https://github.com/fluttercommunity/flutter_launcher_icons/issues/144
#   adaptive_icon_background: "assets/app-icon-background.png"
#   adaptive_icon_foreground: "assets/app-icon-foreground.png"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  # assets:
    # Add assets from the images directory to the application.
    # - assets/
